### PR TITLE
Functions now return request promises instead of logging data to console

### PR DESCRIPTION
**Pull request by Priyadarshanvijay**
Hi, I have included changes required to be made to the code in order to send the Data as JSON to the application instead of logging it into console. Please review it and see if it is acceptable. Thanks!

### CODE REVIEW

**Comment by ba11b0y** [comment]
Thanks for the PR!
I understand that returning a JSON response instead of simply logging to the console is the way to go.
The only problem I see with your PR is that, the response won't be generic.
For instance, after resolution users will have to use different dot notations for different functions.

**Comment by Priyadarshanvijay** [comment]
As far as I can see, the response would be generic only. In the response of each of the API calls, at the top level, there are only two keys: `body` and `head`. I am also pasting a list of all the responses given as example responses in the docs, you can verify from there also: 

Screenshot from 2020-08-27 12-43-40
Hope this helps.

**Comment by Priyadarshanvijay** [comment]
Complete JSON for your ref:
```
{
   "margin":{
      "body":{
         "ClientCode":"12345678",
         "EquityMargin":[
            {
               "ALB":2794.05,
               "Adhoc":0,
               "AvailableMargin":547.75,
               "GHV":52.1,
               "GHVPer":100,
               "GrossMargin":535.73,
               "Mgn4PendOrd":0,
               "Mgn4Position":0.8,
               "OptionsMtoMLoss":0,
               "PDHV":41.68,
               "Payments":-2300,
               "Receipts":0,
               "THV":5427.42
            }
         ],
         "Message":"",
         "Status":0,
         "TimeStamp":"/Date(1556183887614+0530)/"
      },
      "head":{
         "responseCode":"5PMarginV3",
         "status":"0",
         "statusDescription":"Success"
      }
   },
   "orderBook":{
      "body":{
         "Message":"",
         "OrderBookDetail":[
            {
               "AHProcess":"N",
               "AfterHours":"N",
               "AtMarket":"N",
               "BrokerOrderId":90974611,
               "BrokerOrderTime":"/Date(1556174280727+0530)/",
               "BuySell":"S",
               "DelvIntra":"D",
               "DisClosedQty":0,
               "Exch":"N",
               "ExchOrderID":"1100000003274860",
               "ExchOrderTime":"/Date(1556174280000+0530)/",
               "ExchType":"C",
               "MarketLot":1,
               "OldorderQty":1,
               "OrderRequesterCode":"12345678",
               "OrderStatus":"Fully Executed",
               "OrderValidUpto":"25 Apr 2019",
               "OrderValidity":0,
               "PendingQty":0,
               "Qty":1,
               "Rate":52.9,
               "Reason":"",
               "RequestType":"M",
               "SLTriggerRate":0,
               "SLTriggered":"N",
               "SMOProfitRate":0,
               "SMOSLLimitRate":0,
               "SMOSLTriggerRate":0,
               "SMOTrailingSL":0,
               "ScripCode":11184,
               "ScripName":"IDFCFIRSTB",
               "TerminalId":42583,
               "TradedQty":1,
               "WithSL":"N"
            },
            {
               "AHProcess":"N",
               "AfterHours":"N",
               "AtMarket":"N",
               "BrokerOrderId":90975529,
               "BrokerOrderTime":"/Date(1556174345727+0530)/",
               "BuySell":"B",
               "DelvIntra":"D",
               "DisClosedQty":0,
               "Exch":"N",
               "ExchOrderID":"1400000006836412",
               "ExchOrderTime":"/Date(1556166711000+0530)/",
               "ExchType":"D",
               "MarketLot":1,
               "OldorderQty":20,
               "OrderRequesterCode":"C142243",
               "OrderStatus":"Cancelled",
               "OrderValidUpto":"30 Dec 1899",
               "OrderValidity":0,
               "PendingQty":20,
               "Qty":20,
               "Rate":26,
               "Reason":"",
               "RequestType":"C",
               "SLTriggerRate":0,
               "SLTriggered":"N",
               "SMOProfitRate":0,
               "SMOSLLimitRate":0,
               "SMOSLTriggerRate":0,
               "SMOTrailingSL":0,
               "ScripCode":40124,
               "ScripName":"BANKNIFTY 02 May 2019 PE 29500.00",
               "TerminalId":34450,
               "TradedQty":0,
               "WithSL":"N"
            },
            {
               "AHProcess":"N",
               "AfterHours":"N",
               "AtMarket":"N",
               "BrokerOrderId":90979426,
               "BrokerOrderTime":"/Date(1556174647640+0530)/",
               "BuySell":"B",
               "DelvIntra":"D",
               "DisClosedQty":0,
               "Exch":"N",
               "ExchOrderID":"0",
               "ExchOrderTime":"/Date(315513000000+0530)/",
               "ExchType":"D",
               "MarketLot":2,
               "OldorderQty":0,
               "OrderRequesterCode":"123456789",
               "OrderStatus":"Rejected By 5P",
               "OrderValidUpto":"30 Dec 1899",
               "OrderValidity":0,
               "PendingQty":40,
               "Qty":40,
               "Rate":26,
               "Reason":"Order rejected by RMS as margin required is Rs1040, while available margin is Rs526.53",
               "RequestType":"P",
               "SLTriggerRate":0,
               "SLTriggered":"N",
               "SMOProfitRate":0,
               "SMOSLLimitRate":0,
               "SMOSLTriggerRate":0,
               "SMOTrailingSL":0,
               "ScripCode":40124,
               "ScripName":"BANKNIFTY 02 May 2019 PE 29500.00",
               "TerminalId":0,
               "TradedQty":0,
               "WithSL":"N"
            },
            {
               "AHProcess":"N",
               "AfterHours":"N",
               "AtMarket":"N",
               "BrokerOrderId":90980441,
               "BrokerOrderTime":"/Date(1556174735707+0530)/",
               "BuySell":"B",
               "DelvIntra":"D",
               "DisClosedQty":0,
               "Exch":"N",
               "ExchOrderID":"0",
               "ExchOrderTime":"/Date(315513000000+0530)/",
               "ExchType":"D",
               "MarketLot":1,
               "OldorderQty":0,
               "OrderRequesterCode":"12345678",
               "OrderStatus":"Rejected By 5P",
               "OrderValidUpto":"30 Dec 1899",
               "OrderValidity":0,
               "PendingQty":20,
               "Qty":20,
               "Rate":30,
               "Reason":"Order rejected by RMS as margin required is Rs600, while available margin is Rs526.53",
               "RequestType":"P",
               "SLTriggerRate":0,
               "SLTriggered":"N",
               "SMOProfitRate":0,
               "SMOSLLimitRate":0,
               "SMOSLTriggerRate":0,
               "SMOTrailingSL":0,
               "ScripCode":40124,
               "ScripName":"BANKNIFTY 02 May 2019 PE 29500.00",
               "TerminalId":0,
               "TradedQty":0,
               "WithSL":"N"
            },
            {
               "AHProcess":"N",
               "AfterHours":"N",
               "AtMarket":"N",
               "BrokerOrderId":90980925,
               "BrokerOrderTime":"/Date(1556174776827+0530)/",
               "BuySell":"B",
               "DelvIntra":"D",
               "DisClosedQty":0,
               "Exch":"N",
               "ExchOrderID":"1400000024187237",
               "ExchOrderTime":"/Date(1556174752000+0530)/",
               "ExchType":"D",
               "MarketLot":1,
               "OldorderQty":20,
               "OrderRequesterCode":"12345678",
               "OrderStatus":"Cancelled",
               "OrderValidUpto":"30 Dec 1899",
               "OrderValidity":0,
               "PendingQty":20,
               "Qty":20,
               "Rate":26,
               "Reason":"",
               "RequestType":"C",
               "SLTriggerRate":0,
               "SLTriggered":"N",
               "SMOProfitRate":0,
               "SMOSLLimitRate":0,
               "SMOSLTriggerRate":0,
               "SMOTrailingSL":0,
               "ScripCode":40124,
               "ScripName":"BANKNIFTY 02 May 2019 PE 29500.00",
               "TerminalId":34450,
               "TradedQty":0,
               "WithSL":"N"
            },
            {
               "AHProcess":"N",
               "AfterHours":"N",
               "AtMarket":"N",
               "BrokerOrderId":91028378,
               "BrokerOrderTime":"/Date(1556177965000+0530)/",
               "BuySell":"B",
               "DelvIntra":"D",
               "DisClosedQty":0,
               "Exch":"N",
               "ExchOrderID":"0",
               "ExchOrderTime":"/Date(315513000000+0530)/",
               "ExchType":"C",
               "MarketLot":1,
               "OldorderQty":0,
               "OrderRequesterCode":"12345678",
               "OrderStatus":"Rejected By 5P",
               "OrderValidUpto":"25 Apr 2019",
               "OrderValidity":0,
               "PendingQty":1,
               "Qty":1,
               "Rate":1400,
               "Reason":"Order rejected by RMS as margin required is Rs399.98, while available margin is Rs17.75",
               "RequestType":"P",
               "SLTriggerRate":0,
               "SLTriggered":"N",
               "SMOProfitRate":0,
               "SMOSLLimitRate":0,
               "SMOSLTriggerRate":0,
               "SMOTrailingSL":0,
               "ScripCode":2885,
               "ScripName":"RELIANCE",
               "TerminalId":0,
               "TradedQty":0,
               "WithSL":"N"
            },
            {
               "AHProcess":"N",
               "AfterHours":"N",
               "AtMarket":"N",
               "BrokerOrderId":91028710,
               "BrokerOrderTime":"/Date(1556177985650+0530)/",
               "BuySell":"B",
               "DelvIntra":"D",
               "DisClosedQty":0,
               "Exch":"N",
               "ExchOrderID":"0",
               "ExchOrderTime":"/Date(315513000000+0530)/",
               "ExchType":"U",
               "MarketLot":1,
               "OldorderQty":0,
               "OrderRequesterCode":"12345678",
               "OrderStatus":"Rejected By 5P",
               "OrderValidUpto":"30 Dec 1899",
               "OrderValidity":0,
               "PendingQty":1,
               "Qty":1,
               "Rate":69,
               "Reason":"Order rejected by RMS as margin required is Rs1610.13, while available margin is Rs6.52999999999997",
               "RequestType":"P",
               "SLTriggerRate":0,
               "SLTriggered":"N",
               "SMOProfitRate":0,
               "SMOSLLimitRate":0,
               "SMOSLTriggerRate":0,
               "SMOTrailingSL":0,
               "ScripCode":2794,
               "ScripName":"USDINR 25 Apr 2019",
               "TerminalId":0,
               "TradedQty":0,
               "WithSL":"N"
            },
            {
               "AHProcess":"N",
               "AfterHours":"N",
               "AtMarket":"N",
               "BrokerOrderId":91029117,
               "BrokerOrderTime":"/Date(1556178010583+0530)/",
               "BuySell":"B",
               "DelvIntra":"D",
               "DisClosedQty":0,
               "Exch":"N",
               "ExchOrderID":"1400000030807362",
               "ExchOrderTime":"/Date(1556177515000+0530)/",
               "ExchType":"D",
               "MarketLot":1,
               "OldorderQty":20,
               "OrderRequesterCode":"12345678",
               "OrderStatus":"Cancelled",
               "OrderValidUpto":"30 Dec 1899",
               "OrderValidity":0,
               "PendingQty":20,
               "Qty":20,
               "Rate":26,
               "Reason":"",
               "RequestType":"C",
               "SLTriggerRate":0,
               "SLTriggered":"N",
               "SMOProfitRate":0,
               "SMOSLLimitRate":0,
               "SMOSLTriggerRate":0,
               "SMOTrailingSL":0,
               "ScripCode":40124,
               "ScripName":"BANKNIFTY 02 May 2019 PE 29500.00",
               "TerminalId":34450,
               "TradedQty":0,
               "WithSL":"N"
            },
            {
               "AHProcess":"N",
               "AfterHours":"N",
               "AtMarket":"N",
               "BrokerOrderId":91049315,
               "BrokerOrderTime":"/Date(1556179132500+0530)/",
               "BuySell":"B",
               "DelvIntra":"D",
               "DisClosedQty":0,
               "Exch":"N",
               "ExchOrderID":"0",
               "ExchOrderTime":"/Date(315513000000+0530)/",
               "ExchType":"C",
               "MarketLot":2,
               "OldorderQty":0,
               "OrderRequesterCode":"12345678",
               "OrderStatus":"Rejected By 5P",
               "OrderValidUpto":"24 Apr 2019",
               "OrderValidity":0,
               "PendingQty":2,
               "Qty":2,
               "Rate":717.65,
               "Reason":"Order rejected by RMS. Limit price should be within circuit limit(358.7 - 538)",
               "RequestType":"P",
               "SLTriggerRate":0,
               "SLTriggered":"N",
               "SMOProfitRate":0,
               "SMOSLLimitRate":0,
               "SMOSLTriggerRate":0,
               "SMOTrailingSL":0,
               "ScripCode":11809,
               "ScripName":"IIFL",
               "TerminalId":0,
               "TradedQty":0,
               "WithSL":"N"
            },
            {
               "AHProcess":"N",
               "AfterHours":"N",
               "AtMarket":"N",
               "BrokerOrderId":91049576,
               "BrokerOrderTime":"/Date(1556179147060+0530)/",
               "BuySell":"B",
               "DelvIntra":"D",
               "DisClosedQty":0,
               "Exch":"N",
               "ExchOrderID":"0",
               "ExchOrderTime":"/Date(315513000000+0530)/",
               "ExchType":"C",
               "MarketLot":2,
               "OldorderQty":0,
               "OrderRequesterCode":"12345678",
               "OrderStatus":"Rejected By 5P",
               "OrderValidUpto":"24 Apr 2019",
               "OrderValidity":0,
               "PendingQty":2,
               "Qty":2,
               "Rate":366,
               "Reason":"Order rejected by RMS as margin required is Rs732, while available margin is Rs547.75",
               "RequestType":"P",
               "SLTriggerRate":0,
               "SLTriggered":"N",
               "SMOProfitRate":0,
               "SMOSLLimitRate":0,
               "SMOSLTriggerRate":0,
               "SMOTrailingSL":0,
               "ScripCode":11809,
               "ScripName":"IIFL",
               "TerminalId":0,
               "TradedQty":0,
               "WithSL":"N"
            }
         ],
         "Status":0
      },
      "head":{
         "responseCode":"5POrdBkV2",
         "status":"0",
         "statusDescription":"Success"
      }
   },
   "holdings":{
      "body":{
         "CacheTime":300,
         "Data":[
            {
               "BseCode":539437,
               "CurrentPrice":53.2,
               "DPQty":0,
               "Exch":"N",
               "ExchType":"C",
               "FullName":"IDFC FIRST BANK LIMITED",
               "NseCode":11184,
               "POASigned":"N",
               "PoolQty":1,
               "Quantity":1,
               "ScripMultiplier":1,
               "Symbol":"IDFCFIRSTB"
            },
            {
               "BseCode":532081,
               "CurrentPrice":0.19,
               "DPQty":0,
               "Exch":"N",
               "ExchType":"C",
               "FullName":"KSS LIMITED",
               "NseCode":13663,
               "POASigned":"N",
               "PoolQty":10,
               "Quantity":10,
               "ScripMultiplier":1,
               "Symbol":"KSERASERA"
            },
            {
               "BseCode":539351,
               "CurrentPrice":75.25,
               "DPQty":0,
               "Exch":"N",
               "ExchType":"C",
               "FullName":"Prabhat Dairy Limited",
               "NseCode":10650,
               "POASigned":"N",
               "PoolQty":1,
               "Quantity":1,
               "ScripMultiplier":1,
               "Symbol":"PRABHAT"
            }
         ],
         "Message":"Success",
         "Status":0
      },
      "head":{
         "responseCode":"5PHoldingV2",
         "status":"0",
         "statusDescription":"Success"
      }
   },
   "positions":{
      "body":{
         "Message":"",
         "NetPositionDetail":[
            {
               "BodQty":0,
               "BookedPL":0,
               "BuyAvgRate":0,
               "BuyQty":0,
               "BuyValue":0,
               "Exch":"N",
               "ExchType":"C",
               "LTP":52.75,
               "MTOM":0.15,
               "Multiplier":1,
               "NetQty":-1,
               "OrderFor":"D",
               "PreviousClose":52.1,
               "ScripCode":11184,
               "ScripName":"IDFCFIRSTB",
               "SellAvgRate":52.9,
               "SellQty":1,
               "SellValue":52.9
            }
         ],
         "Status":0
      },
      "head":{
         "responseCode":"5PNPNWV1",
         "status":"0",
         "statusDescription":"Success"
      }
   },
   "orderRequest":{
      "body":{
         "BrokerOrderID":91049576,
         "ClientCode":"1234567",
         "Exch":"7",
         "ExchOrderID":"",
         "ExchType":"6",
         "LocalOrderID":0,
         "Message":"Order rejected by RMS as margin required is Rs732, while available margin is Rs547.75",
         "RMSResponseCode":-7,
         "ScripCode":11809,
         "Status":1,
         "Time":"/Date(1556130600000+0530)/"
      },
      "head":{
         "responseCode":"5POrdReq",
         "status":"0",
         "statusDescription":"Success"
      }
   },
   "orderStatus":{
      "body":{
         "Message":"",
         "OrdStatusReqList":[
            {
               "Exch":"N",
               "ExchOrderID":1000000000140570,
               "ExchOrderTime":"/Date(1552999348000+0530)/",
               "ExchType":"C",
               "OrderQty":100,
               "OrderRate":174.6,
               "PendingQty":0,
               "ScripCode":2475,
               "Status":"Modified",
               "Symbol":"ONGC",
               "TradedQty":100
            }
         ],
         "Status":0
      },
      "head":{
         "responseCode":"5POrdStatus",
         "status":"0",
         "statusDescription":"Success"
      }
   },
   "tradeInformation":{
      "body":{
         "Message":"",
         "Status":0,
         "TradeDetail":[
            
         ]
      },
      "head":{
         "responseCode":"5PTrdInfo",
         "status":"0",
         "statusDescription":"Success"
      }
   }
}
```

**Comment by ba11b0y** [comment]
This was introduced in 189834968502b56bec2db838158395891db4d915 
Hence closing this.
Thanks anyways :smile:

**Pull request closed without merging**
